deviseを使ってユーザー認証を実装する
takopom/books_app pull request #3
Opened 2019-09-01 06:42 UTC by takopom

- ユーザ認証機能を実装する
- ユーザのプロフィールページを作る
    - 郵便番号
    - 住所
    - 自己紹介文
- rails本家のrubocopルールを適用する

2019-09-10 06:58 UTC, komagata requested changes

2019-09-10 06:58 UTC, komagata commented on app/assets/javascripts/users.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
こういうscaffoldで出来る系ファイルで必要無いものは削除するのが良さそうです。
特にWeb系では一行でもコードベースを減らすのに心を砕くので、PRで指摘されがちです。

2019-09-10 06:58 UTC, komagata commented on app/helpers/users_helper.rb
> +module UsersHelper
こういうのも実装なければ削除が良さそうです。

2019-09-10 06:58 UTC, komagata commented on config/locales/devise.en.yml
> +# Additional translations at https://github.com/plataformatec/devise/wiki/I18n
こちらのよくあるミスを参照してくださいー

https://bootcamp.fjord.jp/practices/40

2019-09-10 19:24 UTC, takopom commented on config/locales/devise.en.yml
> +# Additional translations at https://github.com/plataformatec/devise/wiki/I18n
ご指摘ありがとうございます🙇‍♀️よくあるミスに記載されている内容で恐縮です😵
・scaffoldで生成される必要のない＆実装のないファイルを削除
・deviseのロケールファイルを削除
いたします。

2019-09-10 19:26 UTC, takopom commented on app/assets/javascripts/users.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
> 特にWeb系では一行でもコードベースを減らすのに心を砕く

心に刻みます…！！！ご指摘ありがとうございます🙇‍♀️

2019-09-11 10:52 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2019-09-11 18:55 UTC, merged